namespace Fiero.Business
{
    public enum ColorName
    {
        White,
        Red,
        Green,
        Blue,
        Cyan,
        Yellow,
        Magenta,
        Gray,
        LightGray,
        LightRed,
        LightGreen,
        LightBlue,
        LightCyan,
        LightYellow,
        LightMagenta,
        Black,
        Transparent,
        UIPrimary,
        UISecondary,
        UIAccent,
        UIBorder,
        UIDisabled,
        UIBackground
    }
}
